print("The war was raging, and countless lives were lost. The cruelest war in human history, World War II, finally came to the end. With the surrender of the Third Reich, people were full of confidence in the end of the war.")
print("The only enemy still resisting was the Empire of Japan. In response, the United States of America planned a series of actions.")
print("Not long ago, they successfully carried out 105 bombings of different scales in Tokyo, directly causing the deaths of about 350,000 to 900,000 soldiers and civilians.")
print("This brutal bombing dealt a great blow to Japan's war confidence, but the ignorant emperor did not intend to surrender and they were still carrying out useless resistance.")
print("It's time! Colonel, we must take action, it's time to put an end to their wishful thinking!")
name = input("Please state your name, Colonel, we are about to carry out the final operation.")
print("The information has been collected, without further ado, let's get started! Colonel",name)
print("You may have heard of the Manhattan Project. Yes, our motherland already possesses unprecedentedly powerful weapons. Now, it is time to make the enemy despair!")
print("Climb aboard this B-29 and bring death to your enemies!")