print("The war was raging, and countless lives were lost. The cruelest war in human history, World War II, finally came to the end. With the surrender of the Third Reich, people were full of confidence in the end of the war.")
input()
print("The only enemy still resisting was the Empire of Japan. In response, the United States of America planned a series of actions.")
input()
print("Not long ago, they successfully carried out 105 bombings of different scales in Tokyo, directly causing the deaths of about 350,000 to 900,000 soldiers and civilians.")
input()
print("This brutal bombing dealt a great blow to Japan's war confidence, but the ignorant emperor did not intend to surrender and they were still carrying out useless resistance.")
input()
print("It's time! Colonel, we must take action, it's time to put an end to their wishful thinking!")
input()
name = input("Please state your name, Colonel, we are about to carry out the final operation.")
print("The information has been collected, without further ado, let's get started! Colonel",name)
input()
print("You may have heard of the Manhattan Project. Yes, our motherland already possesses unprecedentedly powerful weapons. Now, it is time to make the enemy despair!")
input()
print("Climb aboard this B-29 and bring death to your enemies!")
input()
print("The cold wind is howling, the sky in the distance is borederless, and you have already flown over Japan.")
input()
print("You look into the bombing optic, seeing flak bursts and shells below you. As Hiroshima gets closer and closer to the center of the bombing optic, the outcome of the war is in your hand, and you must decide now.")
input()
print("Do you drop the bomb, this will likely end the war, but thousands of people will die.")
input()
print("Or maybe you are too kind that you just can't forgive yourself for killing so many people.")
input()
Choice = input("There is not much time for you to think, you must make the choice now. YES OR NO!")
input()
if Choice == "YES".lower().upper():
    print("The atomic bomb left the bomb bay of the plane and fell from a height of thousands of feet.")
    input()
    print("Soon, journalists from all over the Allied countries reported.")
    input()
    print("The atomic bomb was dropped on Hiroshima on August 6, 1945.")
    input()
    print("This caused hundreds of thousands of deaths and caused great panic in Japan.")
    input()
    print("This is very tragic, countless people died in agony.")
    input()
    print("However, the arrogant Japanese government was still not ready to surrender.")
    input()
    print("You clearly remember the moment the bomb landed, the powerful shock and the mushroom cloud rising into the sky.")
    input()
    print("The lives of thousands of people turned into ashes in the thick smoke at this moment.")
    input()
    print("You are very sure that although this move is intended to end the war as soon as possible, the your bumping heart makes you doubt this move.")
    input()
    print("However, in view of Japan's refusal to change its mind, the US government has decided to drop the second atomic bomb.")
    input()
    print("You are seeing the exact same thing you've seen before, you are in the exact same place you were at before, and you're about to do the same thing you've done before.")
    input()
    print("The bomb bay door's opened again. This time, you feel really uncomfortable, tears fell out from your eyes, and fell down into the sky.")
    Drop = input("It's time, are you going to drop it, YES or NO!")
    if Drop == "YES".lower().upper():
       print("So the reporters continued reporting.")
       input()
       print("In order to end the war as soon as possible, the United States dropped a second atomic bomb on Nagasaki.")
       input()
       print("The explosion killed at least 74,000 people.")
       input()
       print("This dealt a heavy blow to the Japanese army and the people.")
       input()
       print("The Japanese government saw that the situation was already decided, and in order to leave a glimmer of hope for survival, it finally surrendered unconditionally on September 2, 1945.")
       input()
       print("World War II ended")
       input()
       print("Afterwards, Japan's economy withered, food was in short supply, and celebrities were in panic.")
       input()
       print("It took decades to return to normal.")
       input()
       print("It can be seen that the impact of war on society is huge.")
       input()
       print("I wonder if you will regret it when you repeat history again?")
    if Drop == "NO".lower().upper():
       print("With your presistence, Nagasaki luckly avoided from the disaster that is about to happen.")
       input()
       print("So is this for the sake of the precious lives or the evil spirits getaway, the anwser would be shown with time.")
       input()
       print("Thousands of metres below clouds, in Tokoyo, things that are happening on the ground aren't peacefull either.")
       input()
       print("The power of the emperor has been significantly reduced after the bombing of Hiroshima, the first nuclear bomb dropped on Japan")
       input()
       print("The sound of fighting againest the emperor is rising as time passes, for the lives of the residents of Japan, the opposition must take action.")
       input()
       print("The angers that the residents have is like the burning flames, and will sure flood japan with the nuclear bomb on Hiroshima.")
       input()
       print("Not long after, a piece of new flowed here: The opposition has taken over the power of the emperor, thus the emperor had no options left but to sign the abdication edict.")
       input()
       print("The new goverment commited to a quick end to the war, and the unconditional surrender is signed not long after.")
       input()
       print("Following the surrender of Japan, the second world war came to an end.")
       input()
       print("Colonel, your effort have not been wasted. The choice you made saved thousands of Japanese people's life.")
    elif Drop == "":
       print("With your presistence, Nagasaki luckly avoided from the disaster that is about to happen.")
       input()
       print("So is this for the sake of the precious lives or the evil spirits getaway, the anwser would be shown with time.")
       input()
       print("Thousands of metres below clouds, in Tokoyo, things that are happening on the ground aren't peacefull either.")
       input()
       print("The power of the emperor has been significantly reduced after the bombing of Hiroshima, the first nuclear bomb dropped on Japan")
       input()
       print("The sound of fighting againest the emperor is rising as time passes, for the lives of the residents of Japan, the opposition must take action.")
       input()
       print("The angers that the residents have is like the burning flames, and will sure flood japan with the nuclear bomb on Hiroshima.")
       input()
       print("Not long after, a piece of new flowed here: The opposition has taken over the power of the emperor, thus the emperor had no options left but to sign the abdication edict.")
       input()
       print("The new goverment commited to a quick end to the war, and the unconditional surrender is signed not long after.")
       input()
       print("Following the surrender of Japan, the second world war came to an end.")
       input()
       print("Colonel, your effort have not been wasted. The choice you made saved thousands of Japanese people's life.")
if Choice == "NO".lower().upper():
    print("You stopped for a second and ask yourself: We are all human, just why whould I do that to my own kind...")
    input()
    print("So you returned home, and Japan was not hit by the atomic bomb.")
    input()
    print("The president was angry, but there was nothing he could do.")
    input()
    print("After discussion, in order to end the war as soon as possible, the United States finally chose to land in Japan and conduct a ground war.")
    input()
    print("However, Japan still believed that it had the strength to fight and continued to choose to fight.")
    input()
    print("The United States launched a large-scale battle after landing, and most of the Japanese soldiers were killed")
    input()
    print("The United States soon reached the vicinity of Tokyo.")
    input()
    print("Obviously, Japan overestimated its own strength")
    input()
    print("But they still refused to surrender and were ready to fight to the end")
    input()
    print("In the end, no amount of resistance could cover up the gap in power, and the United State soldiers captured the emperor and forces him to surredner.")
    input()
    print("At this point, World War II finally came to an end")
    input()
    print("Indulgence in the devil often only leads to more disasters......")
elif Choice == "":
    print("You just can't decide if can get yourself to kill those people, and you suddenly realizes that you've already flown past Hiroshima. And you see a Mitsubishi KI-83 diving onto you.")
    Action = input("With the 30mm, the b29 instantly got shreded to pieces. You fall off the plane and start falling.")