print("The war was raging, and countless lives were lost. The cruelest war in human history, World War II, finally came to the end. With the surrender of the Third Reich, people were full of confidence in the end of the war.")
input()
print("The only enemy still resisting was the Empire of Japan. In response, the United States of America planned a series of actions.")
input()
print("Not long ago, they successfully carried out 105 bombings of different scales in Tokyo, directly causing the deaths of about 350,000 to 900,000 soldiers and civilians.")
input()
print("This brutal bombing dealt a great blow to Japan's war confidence, but the ignorant emperor did not intend to surrender and they were still carrying out useless resistance.")
input()
print("It's time! Colonel, we must take action, it's time to put an end to their wishful thinking!")
input()
name = input("Please state your name, Colonel, we are about to carry out the final operation.")
print("The information has been collected, without further ado, let's get started! Colonel",name)
input()
print("You may have heard of the Manhattan Project. Yes, our motherland already possesses unprecedentedly powerful weapons. Now, it is time to make the enemy despair!")
input()
print("Climb aboard this B-29 and bring death to your enemies!")
input()
print("The cold wind is howling, the sky in the distance is borederless, and you have already flown over Japan.")
input()
print("You look into the bombing optic, seeing flak bursts and shells below you. As Hiroshima gets closer and closer to the center of the bombing optic, the outcome of the war is in your hand, and you must decide now.")
input()
print("Do you drop the bomb, this will likely end the war, but thousands of people will die.")
input()
print("Or maybe you are too kind that you just can't forgive yourself for killing so many people.")
input()
Choice = input("There is not much time for you to think, you must make the choice now.")
input()
if Choice == "Yes".lower():
    print("You dropped the bomb.")
    print("The first atomic bomb was dropped on Hiroshima on August 6, 1945.")
    input()
    print("This caused hundreds of thousands of deaths and caused great panic in Japan.")
    input()
    print("This is very tragic, countless people died in agony.")
    input()
    print("But the Empire of Japan was determined not to surrender and was ready to fight the United States to the end")
    input()
    print("In order to end the war as soon as possible, the United States dropped a second atomic bomb on Nagasaki.")
    input()
    print("The explosion killed at least 74,000 people.")
    input()
    print("This dealt a heavy blow to the Japanese army and the people.")
    input()
    print("The Japanese government saw that the situation was already decided, and in order to leave a glimmer of hope for survival, it finally surrendered unconditionally on September 2, 1945.")
    input()
    print("World War II ended")
    input()
    print("Afterwards, Japan's economy withered, food was in short supply, and celebrities were in panic.")
    input()
    print("It took decades to return to normal.")
    input()
    print("It can be seen that the impact of war on society is huge.")
if Choice == "No".lower():
     print("You stopped for a second and ask yourself: We are all human, just why whould I do that to my own kind...")
elif Choice == "":
     print("You just can't decide if can get yourself to kill those people, and you suddenly realizes that you've already flown past Hiroshima. And you see a Mitsubishi KI-83 diving onto you.")
     Action = input("With the 30mm, the b29 instantly got shreded to pieces. You fall off the plane and start falling.")